/*
### ### ### ### ### ### ###
SourceItFresh - Copyright (C) 2020
This SiF file is licensed under v3 of the GNU Affero General Public License.
### ### ###
GNU AGPLv3 lets people do almost anything they want with the project, except distributing closed-source versions.

Permissions of this strongest copyleft license are conditioned on:
Making available the complete source code of works and modifications, 
 which include larger works using a licensed work, under the same license.
Copyright and license notices must be preserved.
Contributors provide an express grant of patent rights.
When a modified version is used to provide a service over a network,
 the complete source code of the modified version must be made available.

This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY,
 without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
### ### ###
See LICENSE.txt for more details or visit <https://www.gnu.org/licenses/>
### ### ### ### ### ### ###
*/

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiF_Common_RCL.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationCultureEN
    {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationCultureEN() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SiF_Common_RCL.ResourceFiles.LocalizationCultureEN", typeof(LocalizationCultureEN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discover.
        /// </summary>
        internal static string Areas_Base_Discover {
            get {
                return ResourceManager.GetString("Areas:Base:Discover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn.
        /// </summary>
        internal static string Areas_Base_Learn {
            get {
                return ResourceManager.GetString("Areas:Base:Learn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string Areas_Core_Help {
            get {
                return ResourceManager.GetString("Areas:Core:Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        internal static string Areas_Core_Identity {
            get {
                return ResourceManager.GetString("Areas:Core:Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Areas_Core_Login {
            get {
                return ResourceManager.GetString("Areas:Core:Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add-Ins.
        /// </summary>
        internal static string Base_Configure_AddIns {
            get {
                return ResourceManager.GetString("Base:Configure:AddIns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Services.
        /// </summary>
        internal static string Base_Configure_PaidServices {
            get {
                return ResourceManager.GetString("Base:Configure:PaidServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setting.
        /// </summary>
        internal static string Base_Configure_Setting {
            get {
                return ResourceManager.GetString("Base:Configure:Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commodities.
        /// </summary>
        internal static string Base_Manage_Commodities {
            get {
                return ResourceManager.GetString("Base:Manage:Commodities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Farm.
        /// </summary>
        internal static string Base_Manage_Farm {
            get {
                return ResourceManager.GetString("Base:Manage:Farm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        internal static string Base_ManageOrg_Accounts {
            get {
                return ResourceManager.GetString("Base:ManageOrg:Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Logs.
        /// </summary>
        internal static string Base_ManageOrg_ActionLogs {
            get {
                return ResourceManager.GetString("Base:ManageOrg:ActionLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trader Entity.
        /// </summary>
        internal static string Base_ManageOrg_TraderEntity {
            get {
                return ResourceManager.GetString("Base:ManageOrg:TraderEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer.
        /// </summary>
        internal static string Base_Market_Consumer {
            get {
                return ResourceManager.GetString("Base:Market:Consumer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendor.
        /// </summary>
        internal static string Base_Market_Vendor {
            get {
                return ResourceManager.GetString("Base:Market:Vendor", resourceCulture);
            }
        }
    }
}
