CREATE TABLE [dbo].[GoldPriceZ] (
    [Id]                                UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID() PRIMARY KEY,
    [ounce_price_usd]                   DECIMAL (18, 6)  NOT NULL,
    [gmt_ounce_price_usd_updated]       DATETIME         NOT NULL,
    [ounce_price_ask]                   DECIMAL (18, 6)  NOT NULL,
    [ounce_price_bid]                   DECIMAL (18, 6)  NOT NULL,
    [ounce_price_usd_today_low]         DECIMAL (18, 6)  NOT NULL,
    [ounce_price_usd_today_high]        DECIMAL (18, 6)  NOT NULL,
    [usd_to_gbp]                        DECIMAL (18, 12) NULL,
    [usd_to_zar]                        DECIMAL (18, 6)  NULL,
    [gmt_gbp_updated]                   DATETIME         NULL,
    [gmt_zar_updated]                   DATETIME         NULL,
    [ounce_in_gbp]                      DECIMAL (38, 18) NULL,
    [ounce_in_zar]                      DECIMAL (38, 18) NULL,
    [gram_to_ounce_formula]             DECIMAL (38, 18) NULL,
    [gram_in_usd]                       DECIMAL (38, 18) NULL,
    [gram_in_gbp]                       DECIMAL (38, 18) NULL,
    [gram_in_zar]                       DECIMAL (38, 18) NULL,
    [kg_to_ounce_formula]               DECIMAL (38, 18) NULL,
    [kg_in_usd]                         DECIMAL (38, 18) NULL,
    [kg_in_gbp]                         DECIMAL (38, 18) NULL,
    [kg_in_zar]                         DECIMAL (38, 18) NULL,
    [grain_to_ounce_formula]            DECIMAL (38, 18) NULL,
    [grain_in_usd]                      DECIMAL (38, 18) NULL,
    [grain_in_gbp]                      DECIMAL (38, 18) NULL,
    [grain_in_zar]                      DECIMAL (38, 18) NULL,
    [tael-hongkong_to_ounce_formula]    DECIMAL (38, 18) NULL,
    [tael-hongkong_in_usd]              DECIMAL (38, 18) NULL,
    [tael-hongkong_in_gbp]              DECIMAL (38, 18) NULL,
    [tael-hongkong_in_zar]              DECIMAL (38, 18) NULL,
    [tael-japan_to_ounce_formula]       DECIMAL (38, 18) NULL,
    [tael-japan_in_usd]                 DECIMAL (38, 18) NULL,
    [tael-japan_in_gbp]                 DECIMAL (38, 18) NULL,
    [tael-japan_in_zar]                 DECIMAL (38, 18) NULL,
    [tola-india_to_ounce_formula]       DECIMAL (38, 18) NULL,
    [tola-india_in_usd]                 DECIMAL (38, 18) NULL,
    [tola-india_in_gbp]                 DECIMAL (38, 18) NULL,
    [tola-india_in_zar]                 DECIMAL (38, 18) NULL,
    [tola-pakistan_to_ounce_formula]    DECIMAL (38, 18) NULL,
    [tola-pakistan_in_usd]              DECIMAL (38, 18) NULL,
    [tola-pakistan_in_gbp]              DECIMAL (38, 18) NULL,
    [tola-pakistan_in_zar]              DECIMAL (38, 18) NULL,
    [masha_to_ounce_formula]            DECIMAL (38, 18) NULL,
    [masha_in_usd]                      DECIMAL (38, 18) NULL,
    [masha_in_gbp]                      DECIMAL (38, 18) NULL,
    [masha_in_zar]                      DECIMAL (38, 18) NULL,
    [ratti_to_ounce_formula]            DECIMAL (38, 18) NULL,
    [ratti_in_usd]                      DECIMAL (38, 18) NULL,
    [ratti_in_gbp]                      DECIMAL (38, 18) NULL,
    [ratti_in_zar]                      DECIMAL (38, 18) NULL,

    [silver_ounce_in_gbp]               DECIMAL (38, 18) NULL,
    [silver_ounce_in_zar]               DECIMAL (38, 18) NULL,
    [silver_gram_in_usd]                DECIMAL (38, 18) NULL,
    [silver_gram_in_gbp]                DECIMAL (38, 18) NULL,
    [silver_gram_in_zar]                DECIMAL (38, 18) NULL,

    [silver_ounce_price_ask_gbp]        DECIMAL (38, 18) NULL,
    [silver_ounce_price_bid_gbp]        DECIMAL (38, 18) NULL,
    [silver_ounce_price_gbp_today_low]  DECIMAL (38, 18) NULL,
    [silver_ounce_price_gbp_today_high] DECIMAL (38, 18) NULL,

    [silver_ounce_price_ask_zar]        DECIMAL (38, 18) NULL,
    [silver_ounce_price_bid_zar]        DECIMAL (38, 18) NULL,
    [silver_ounce_price_zar_today_low]  DECIMAL (38, 18) NULL,
    [silver_ounce_price_zar_today_high] DECIMAL (38, 18) NULL
);